apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
  - image: mahmoodads/auth
    context: auth
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
    docker:
      dockerfile: dockerfile
  - image: mahmoodads/client
    context: client
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: dockerfile
  - image: mahmoodads/tickets
    context: tickets
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: dockerfile
  - image: mahmoodads/orders
    context: orders
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: dockerfile
  - image: mahmoodads/expiration
    context: expiration
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: dockerfile
  - image: mahmoodads/payments
    context: payments
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: dockerfile
  local:
    push: false
manifests:
  rawYaml:
  - ./infra/k8s/*
  - ./infra/k8s-prod/*
deploy:
  kubectl: {}

### NEUE SERVICES ### 
#  - image: mahmoodads/tickets
#     context: tickets
#     sync:
#       manual:
#       - src: '**/*.js'
#         dest: .
#     docker:
#       dockerfile: dockerfile 
