name: deploy-auth

on: 
  push:
    branches:
      - main
    path:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t mma/auth . 
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker tag mma/auth mahmoodads/auth && docker push mahmoodads/auth 
