name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # - run: |
      #     # Secrets in Kubernetes mit kubectl erstellen
      #     kubectl create secret generic jwt-secret --from-literal=JWT_KEY=${{ secrets.JWT_SECRET }}
      #     kubectl create secret generic stripe-secret --from-literal=STRIPE_KEY=${{ secrets.STRIPE_KEY }}

      - run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_ID }}
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
